FROM node:alpine3.20
WORKDIR /mastermindserver
COPY package*.json .
RUN npm install
#RUN npm install pm2 -g   apparement pas necessaire
COPY . .

#CMD [ "npm","run","prod" ]
CMD [ "node", "src/index.js" ]
EXPOSE 80
