server {
    listen 80;
    server_name _;

    # Chemin racine pointant sur le dossier public
    root /usr/share/nginx/html/public;
    index index.html;

    # Gérer les routes SPA
    location / {
        try_files $uri /index.html;
    }

    # Gestion des fichiers statiques
    location /static/ {
        expires max;
        access_log off;
    }

    # Gérer les erreurs (404 notamment)
    error_page 404 /index.html;
}
