name: CI/CD mastermind workflow
on:
   push:
      branches:
         - main
jobs:
   build:
      runs-on: ubuntu-latest
      permissions:
         packages: write
      strategy:
         matrix:
            include:
               - path: 'mastermindclient'
                 full-image-name: ghcr.io/${{ github.repository }}/mastermindclient
               - path: 'mastermindserver'
                 full-image-name: ghcr.io/${{ github.repository }}/mastermindserver
               - path: 'reverse-proxy'
                 full-image-name: ghcr.io/${{ github.repository }}/reverse-proxy
      steps:
         - name: checkout code
           uses: actions/checkout@v4

         - name: mis en place de buildx
           uses: docker/setup-buildx-action@v3

         - name: login sur github packages Registry
           uses: docker/login-action@v3
           with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{ secrets.GITHUB_TOKEN }}

         - name: récupérationdes metadonnées
           id: metadata
           uses: docker/metadata-action@v5
           with:
              image: ${{ matrix.full_image_name }}

         - name: build et push
           uses: docker/build-push-action@v5
           with:
              push: true
              tags: ${{ matrix.full_image_name }}:latest
              context: ./${{matrix.path}}
              file: ./${{matrix.path}}/Dockerfile.prod
              cache-from: type=gha
              cache-to: type=gha,mode=max
