name: CI/CD mastermind workflow
on:
   push:
      branches:
         - main
env:
   SERVER_IP: 15.235.198.17
   SERVER_USER: ubuntu

jobs:
   test_mastermindClient:
      runs-on: ubuntu-latest
      defaults:
         run:
            working-directory: mastermindclient
      steps:
         - name: checkout code
           uses: actions/checkout@v4
         - name: installer Node.js
           uses: actions/setup-node@v3
           with:
              cache: 'npm'
              cache-dependency-path: mastermindclient/package-lock.json
         - name: installer les dépendances
           run: npm ci --prefer-offline
         - name: check folders
           run: ls /home/runner/work/mastermind/mastermind/mastermindclient/
         - name: afficher l'arborescence des dossiers
           run: ls -R
         - name: exécute les tests
           run: npm run test

   build:
      needs: test_mastermindClient
      runs-on: ubuntu-latest
      permissions:
         packages: write
      strategy:
         matrix:
            include:
               - path: 'mastermindclient'
                 full-image-name: ghcr.io/${{ github.repository }}/mastermindclient
               - path: 'mastermindserver'
                 full-image-name: ghcr.io/${{ github.repository }}/mastermindserver

      steps:
         - name: checkout code
           uses: actions/checkout@v4

         - name: mis en place de buildx
           uses: docker/setup-buildx-action@v3

         - name: login sur github packages Registry
           uses: docker/login-action@v3
           with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{ secrets.GITHUB_TOKEN }}

         - name: récupérationdes metadonnées
           id: metadata
           uses: docker/metadata-action@v5
           with:
              images: ${{ matrix.full-image-name }}

         - name: build et push
           uses: docker/build-push-action@v5
           with:
              push: true
              tags: ${{ matrix.full-image-name }}:latest
              context: ./${{matrix.path}}
              file: ./${{matrix.path}}/Dockerfile.prod
              cache-from: type=gha
              cache-to: type=gha,mode=max
   deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
         - name: checkout le code
           uses: actions/checkout@v4

         - name: déployer sur le vps
           run: |
              eval $(ssh-agent -s)
              ssh-add - <<< "${{ secrets.OVH_PROD_PKEY}}"
              mkdir -p  ~/.ssh
              ssh-keyscan -H ${{ env.SERVER_IP }} >> ~/.ssh/known_hosts
              scp compose.prod2.yml ${{ env.SERVER_USER }}@${{ env.SERVER_IP }}:/home/${{ env.SERVER_USER }}/compose.prod2.yml
              ssh ${{ env.SERVER_USER }}@${{ env.SERVER_IP }} "
              export DB_USERNAME=${{ secrets.DB_USERNAME }} 
              export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
              export MODE_ENV=${{ secrets.MODE_ENV }}
              export DB_PROD=${{ secrets.DB_PROD }}
              export DB_DEV=${{ secrets.DB_DEV }}
              export JWTPRIVATEKEY=\$(echo \"${{ secrets.JWTPRIVATEKEYBASE64 }}\" | base64 -d)
              export JWTPUBLICKEY=\$(echo \"${{ secrets.JWTPUBLICKEYBASE64 }}\" | base64 -d)
              export MONGO_INITDB_ROOT_USERNAME=${{secrets.MONGO_INITDB_ROOT_USERNAME}}
              export MONGO_INITDB_ROOT_PASSWORD=${{secrets.MONGO_INITDB_ROOT_PASSWORD}}
              docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} &&

              docker compose -f /home/${{ env.SERVER_USER }}/compose.prod2.yml up -d --force-recreate"
